### ISSUE TITLE
Does not find my plantuml

### ISSUE THREAD

**Issue by Zearin** [cb109/pyplantuml#1]
I am excited that this tool exists!  Unfortunately, it is not working for me at the moment. :/

It is not finding my `plantuml`, which is most _definitely_ on my `PATH`.  However, before that error message, I get a TON of repeats of something like the following error message:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/astroid/manager.py", line 43, in astroid_wrapper
    return func(modname)
  File "/usr/local/lib/python3.5/site-packages/astroid/manager.py", line 111, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File "/usr/local/lib/python3.5/site-packages/astroid/builder.py", line 134, in file_build
    module = self._data_build(data, modname, path)
  File "/usr/local/lib/python3.5/site-packages/astroid/builder.py", line 177, in _data_build
    module = rebuilder.visit_module(node, modname, node_file, package)
  File "/usr/local/lib/python3.5/site-packages/astroid/rebuilder.py", line 146, in visit_module
    newnode.body = [self.visit(child, newnode) for child in node.body]
  File "/usr/local/lib/python3.5/site-packages/astroid/rebuilder.py", line 146, in <listcomp>
    newnode.body = [self.visit(child, newnode) for child in node.body]
  File "/usr/local/lib/python3.5/site-packages/astroid/rebuilder.py", line 159, in visit
    return self._transform(visit_method(node, parent))
  File "/usr/local/lib/python3.5/site-packages/astroid/rebuilder.py", line 865, in visit_try
    newnode.body = [self.visit(child, newnode) for child in node.body]
  File "/usr/local/lib/python3.5/site-packages/astroid/rebuilder.py", line 865, in <listcomp>
    newnode.body = [self.visit(child, newnode) for child in node.body]
  File "/usr/local/lib/python3.5/site-packages/astroid/rebuilder.py", line 159, in visit
    return self._transform(visit_method(node, parent))
  File "/usr/local/lib/python3.5/site-packages/astroid/rebuilder.py", line 236, in visit_assign
    newnode.value = self.visit(node.value, newnode)
  File "/usr/local/lib/python3.5/site-packages/astroid/rebuilder.py", line 159, in visit
    return self._transform(visit_method(node, parent))
  File "/usr/local/lib/python3.5/site-packages/astroid/rebuilder.py", line 311, in visit_callfunc
    if node.starargs is not None:
AttributeError: 'Call' object has no attribute 'starers'
```
- Running on OS X
- [Homebrew](http://brew.sh) installation of Python 3 and `plantuml`
- attempted use on a Python 3 project (with function- and return-annotations—the first project I’ve used annotations in, so I dunno if it’s significant)

Let me know if there’s any other info that would be helpful.

**Comment by cb109** [comment]
Hi @Zearin, glad you like the idea. I have no way to test on OS X myself, but I have a feeling why this may not work for you:
- I don't know how plantuml is installed via homebrew, but pyplantuml is looking for `plantuml.jar` not `plantuml`. See `writer.py:getLocalPlantUmlPath()`
- The astroid/pyreverse version I am using within this tool is pretty old. I tried to update some time ago but the internal API changes broke the project, so I pinned the version for the moment. If you have a newer astroid version installed, that would most likely be the reason of failure.
